[target.x86_64-unknown-linux-musl]
rustflags = ["-Clink-arg=-s"]

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"
rustflags = ["-Clink-arg=-s"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]
